# Generated by Django 5.1.2 on 2024-11-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_match_country1_remove_match_country2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winners',
            field=models.ManyToManyField(related_name='match_wins', to='game.country'),
        ),
    ]
