# Generated by Django 5.1.2 on 2024-11-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_match_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='championship',
            name='guesses',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
