# Generated by Django 5.1.2 on 2024-12-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_country_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
